"""empty message

Revision ID: 058a120fa19d
Revises: 0e7a9b8e5c9e
Create Date: 2022-01-31 13:01:47.599792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058a120fa19d'
down_revision = '0e7a9b8e5c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('music_room_name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_rooms')
    # ### end Alembic commands ###
